[package]
name = "async-range-request-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
futures = "0.3.30"

[dev-dependencies]
tokio = { version = "1.38.0", features = ["full"] }
